[package]
name = "rtx_remix_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
colored = "2.0"
indicatif = "0.17"
zip = "0.6"