name: 'Build and Upload'
on:
    push:
        branches:
            - "kamil-patch"  # You can add more branches here if needed

jobs:
    build_and_upload:
        name: 'Build and Upload'
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Build binary
              run: |
                pyinstaller --onefile -i NONE -n "RTX Remix Downloader" ./main.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: RTX-Remix-Downloader
                path: ./dist/RTX Remix Downloader.exe
                if-no-files-found: error

            - name: Get commit hash
              id: commit
              run: echo "hash=${{ github.sha }}" >> $GITHUB_OUTPUT

            - name: Upload to release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ steps.commit.outputs.hash }}
                files: ./dist/RTX Remix Downloader.exe
                generate_release_notes: false
